#!/bin/sh -e
# Uploads generated pages to gh-pages branch. Thx @erikrose and @pmac

cd docs
git init
git config user.name "schalkneethling"
git config user.email "sneethling@mozilla.com"
git checkout -b gh-pages
git add .
git commit -m "Deploying latest generated pages"
git remote add mdn "https://$GITHUB_TOKEN@github.com/mdn/interactive-examples.git"
# Eat output so it doesn't spit out the sensitive GH_TOKEN if something goes wrong:
git push -q -f mdn gh-pages > /dev/null 2>&1
